project:
  type: website
  output-dir: docs

website:
  title: "Assistant to the Regional Data Manager"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - favorites.qmd
format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofont: courier new
    backgroundcolor: "#a5aaac"
    css: styles.css
    toc: true



